#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///

# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Generate testing/src/scenario/_charmcraft_extensions.py.

For each charmcraft extension profile (django-framework, fastapi-framework, etc.),
this script runs `charmcraft init` and `charmcraft expand-extensions` in a temp
directory, then extracts the metadata, config, and actions that the extension adds.

The output module contains three dictionaries per extension:
  METADATA: dict[str, dict]   - containers, peers, provides, requires, resources, assumes
  CONFIG:   dict[str, dict]   - config options added by each extension
  ACTIONS:  dict[str, dict]   - actions added by each extension
"""

from __future__ import annotations

import pathlib
import pprint
import subprocess
import tempfile

import yaml

# Keys from the expanded YAML that belong to "metadata" (the charm's metadata.yaml equivalent).
METADATA_KEYS = {
    'assumes',
    'containers',
    'peers',
    'provides',
    'requires',
    'resources',
}

# Keys that are user-provided or build-related (not extension-contributed metadata).
IGNORED_KEYS = {
    'name',
    'summary',
    'description',
    'type',
    'bases',
    'base',
    'platforms',
    'extensions',
    'parts',
    'charm-libs',
}

OUTPUT_FILE = (
    pathlib.Path(__file__).resolve().parent.parent
    / 'testing'
    / 'src'
    / 'scenario'
    / '_charmcraft_extensions.py'
)


def get_extensions() -> list[str]:
    """Get the list of available charmcraft extensions via ``charmcraft list-extensions``."""
    result = subprocess.run(
        ['charmcraft', 'list-extensions'],
        check=True,
        capture_output=True,
        text=True,
    )
    extensions = []
    for line in result.stdout.splitlines():
        # Skip header and separator lines.
        if not line or line.startswith('Extension') or line.startswith('---'):
            continue
        name = line.split()[0]
        extensions.append(name)
    return sorted(extensions)


def run_charmcraft(profile: str, workdir: pathlib.Path) -> dict:
    """Run charmcraft init + expand-extensions and return the expanded YAML as a dict."""
    subprocess.run(
        ['charmcraft', 'init', '--profile', profile, '--name', 'test-charm'],
        cwd=workdir,
        check=True,
        capture_output=True,
        text=True,
    )
    result = subprocess.run(
        ['charmcraft', 'expand-extensions'],
        cwd=workdir,
        check=True,
        capture_output=True,
        text=True,
    )
    return yaml.safe_load(result.stdout)


def extract_extension_data(expanded: dict) -> tuple[dict, dict, dict]:
    """Extract metadata, config options, and actions from expanded charmcraft YAML."""
    metadata = {}
    for key in METADATA_KEYS:
        if key in expanded:
            metadata[key] = expanded[key]

    config = {}
    if 'config' in expanded and 'options' in expanded['config']:
        config = expanded['config']['options']

    actions = expanded.get('actions', {})

    return metadata, config, actions


def format_dict(d: dict, indent: int = 4) -> str:
    """Format a dict as a Python literal string."""
    formatted = pprint.pformat(d, width=100, sort_dicts=True)
    if '\n' in formatted:
        lines = formatted.splitlines()
        result = lines[0]
        for line in lines[1:]:
            result += '\n' + ' ' * indent + line
        return result
    return formatted


def generate_module(all_data: dict[str, tuple[dict, dict, dict]]) -> str:
    """Generate the Python module source code."""
    lines = [
        '# Copyright 2026 Canonical Ltd.',
        '# See LICENSE file for licensing details.',
        '"""Charmcraft extension metadata, config, and actions.',
        '',
        'Auto-generated by .github/generate_charmcraft_extensions.py',
        'Do not edit manually.',
        '"""',
        '',
        'from __future__ import annotations',
        '',
    ]

    # Build the three top-level dicts.
    metadata_entries = {}
    config_entries = {}
    action_entries = {}
    for profile, (metadata, config, actions) in sorted(all_data.items()):
        metadata_entries[profile] = metadata
        config_entries[profile] = config
        action_entries[profile] = actions

    for var_name, data, docstring in [
        (
            'METADATA',
            metadata_entries,
            'Metadata added by each charmcraft extension.',
        ),
        ('CONFIG', config_entries, 'Config options added by each charmcraft extension.'),
        ('ACTIONS', action_entries, 'Actions added by each charmcraft extension.'),
    ]:
        lines.append(f'# {docstring}')
        lines.append(f'{var_name}: dict[str, dict] = {{')
        for profile in sorted(data):
            lines.append(f'    {profile!r}: {{')
            for key in sorted(data[profile]):
                val = data[profile][key]
                formatted = format_dict(val, indent=8)
                lines.append(f'        {key!r}: {formatted},')
            lines.append('    },')
        lines.append('}')
        lines.append('')

    return '\n'.join(lines)


def main() -> int:  # noqa: D103
    extensions = get_extensions()
    print(f'Found extensions: {", ".join(extensions)}')

    all_data: dict[str, tuple[dict, dict, dict]] = {}

    for profile in extensions:
        print(f'Processing {profile}...')
        with tempfile.TemporaryDirectory() as tmpdir:
            expanded = run_charmcraft(profile, pathlib.Path(tmpdir))
            all_data[profile] = extract_extension_data(expanded)

    module_source = generate_module(all_data)

    if OUTPUT_FILE.exists():
        response = input(f'{OUTPUT_FILE} already exists. Overwrite? [y/N] ').strip().lower()
        if response != 'y':
            print('Aborted.')
            return 1

    OUTPUT_FILE.write_text(module_source)
    print(f'Written to {OUTPUT_FILE}')

    print('Running tox -e format...')
    subprocess.run(
        ['tox', '-e', 'format', '--', str(OUTPUT_FILE)],
        cwd=OUTPUT_FILE.parent,
        check=True,
    )

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
