#!/usr/bin/env -S uv run --script --no-project
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///

# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Generate testing/src/scenario/_charmcraft_extensions.py.

For each charmcraft extension profile (django-framework, fastapi-framework, etc.),
this script runs `charmcraft init` and `charmcraft expand-extensions` in a temp
directory, then extracts the metadata, config, and actions that the extension adds.

The output module contains three dictionaries per extension:
  METADATA: dict[str, dict]   - containers, peers, provides, requires, resources, assumes
  CONFIG:   dict[str, dict]   - config options added by each extension
  ACTIONS:  dict[str, dict]   - actions added by each extension
"""

from __future__ import annotations

import pathlib
import pprint
import subprocess
import tempfile
from typing import Any

import yaml

# Keys from the expanded YAML that belong to "metadata" (the charm's metadata.yaml equivalent).
METADATA_KEYS = {
    'assumes',
    'containers',
    'peers',
    'provides',
    'requires',
    'resources',
}

# Keys that are user-provided or build-related (not extension-contributed metadata).
IGNORED_KEYS = {
    'name',
    'summary',
    'description',
    'type',
    'bases',
    'base',
    'platforms',
    'extensions',
    'parts',
    'charm-libs',
}

OUTPUT_FILE = (
    pathlib.Path(__file__).resolve().parent.parent
    / 'testing'
    / 'src'
    / 'scenario'
    / '_charmcraft_extensions.py'
)


def get_extensions() -> list[str]:
    """Get the list of available charmcraft extensions via ``charmcraft list-extensions``."""
    result = subprocess.run(
        ['charmcraft', 'list-extensions'],
        check=True,
        capture_output=True,
        text=True,
    )
    extensions = []
    for line in result.stdout.splitlines():
        # Skip header and separator lines.
        if not line or line.startswith('Extension') or line.startswith('---'):
            continue
        name = line.split()[0]
        extensions.append(name)
    return sorted(extensions)


def run_charmcraft(profile: str, workdir: pathlib.Path) -> dict[str, Any]:
    """Run charmcraft init + expand-extensions and return the expanded YAML as a dict."""
    subprocess.check_call(
        ['charmcraft', 'init', '--profile', profile, '--name', 'test-charm'],
        cwd=workdir,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    output = subprocess.check_output(
        ['charmcraft', 'expand-extensions'],
        cwd=workdir,
        text=True,
        stderr=subprocess.DEVNULL,
    )
    return yaml.safe_load(output)


def extract_extension_data(
    expanded: dict[str, Any],
) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    """Extract metadata, config options, and actions from expanded charmcraft YAML."""
    metadata = {key: expanded[key] for key in METADATA_KEYS if key in expanded}
    config = expanded.get('config', {}).get('options', {})
    actions: dict[str, Any] = expanded.get('actions', {})

    return metadata, config, actions


def format_dict(d: dict[str, Any], indent: int = 4) -> str:
    """Format a dict as a Python literal string."""
    formatted = pprint.pformat(d, width=100, sort_dicts=True)
    if '\n' in formatted:
        lines = formatted.splitlines()
        result = lines[0]
        for line in lines[1:]:
            result += '\n' + ' ' * indent + line
        return result
    return formatted


def generate_module(
    all_data: dict[str, tuple[dict[str, Any], dict[str, Any], dict[str, Any]]],
) -> str:
    """Generate the Python module source code."""
    lines = [
        '# Copyright 2026 Canonical Ltd.',
        '# See LICENSE file for licensing details.',
        '"""Charmcraft extension metadata, config, and actions.',
        '',
        'Auto-generated by .github/generate_charmcraft_extensions.py',
        'Do not edit manually.',
        '"""',
        '',
        'from __future__ import annotations',
        '',
        'from typing import Any',
        '',
    ]

    # Build the three top-level dicts.
    metadata_entries: dict[str, dict[str, Any]] = {}
    config_entries: dict[str, dict[str, Any]] = {}
    action_entries: dict[str, dict[str, Any]] = {}
    for profile, (metadata, config, actions) in sorted(all_data.items()):
        metadata_entries[profile] = metadata
        config_entries[profile] = config
        action_entries[profile] = actions

    for var_name, data, doc_name in [
        ('METADATA', metadata_entries, 'Metadata'),
        ('CONFIG', config_entries, 'Config options'),
        ('ACTIONS', action_entries, 'Actions'),
    ]:
        lines.append(f'# {doc_name} added by each charmcraft extension.')
        lines.append(f'{var_name}: dict[str, dict[str, Any]] = {{')
        for profile in sorted(data):
            lines.append(f'    {profile!r}: {{')
            for key in sorted(data[profile]):
                val = data[profile][key]
                formatted = format_dict(val, indent=8)
                lines.append(f'        {key!r}: {formatted},')
            lines.append('    },')
        lines.append('}')
        lines.append('')

    return '\n'.join(lines)


def main() -> int:  # noqa: D103
    extensions = get_extensions()
    print(f'Found extensions: {", ".join(extensions)}')

    all_data: dict[str, tuple[dict[str, Any], dict[str, Any], dict[str, Any]]] = {}

    for profile in extensions:
        print(f'Processing {profile}...')
        with tempfile.TemporaryDirectory() as tmpdir:
            expanded = run_charmcraft(profile, pathlib.Path(tmpdir))
            all_data[profile] = extract_extension_data(expanded)

    module_source = generate_module(all_data)

    if OUTPUT_FILE.exists():
        response = input(f'{OUTPUT_FILE} already exists. Overwrite? [y/N] ').strip().lower()
        if response != 'y':
            print('Aborted.')
            return 1

    OUTPUT_FILE.write_text(module_source)
    print(f'Written to {OUTPUT_FILE}')

    print('Running tox -e format...')
    subprocess.run(
        ['tox', '-e', 'format', '--', str(OUTPUT_FILE)],
        cwd=OUTPUT_FILE.parent,
        check=True,
    )

    return 0


if __name__ == '__main__':
    sys.exit(main())
