version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    create_environment:
       - asdf plugin add uv
       - asdf install uv latest
       - asdf global uv latest
    build:
      html:
         - uvx tox -e docs
