clients:
  sbom:
      service_url: https://sbom-request.canonical.com
      department: charm_engineering
      email: tony.meyer@canonical.com
      team: charm_tech
  secscan: {}


artifacts:
  - name: ops
    type: sdist
    version: 2.22.0
    compression: gz

  - name: ops-scenario
    type: sdist
    version: 7.22.0
    compression: gz

  - name: ops-tracing
    type: sdist
    version: 2.22.0
    compression: gz
