clients:
  sbom:
      service_url: https://sbom-request.canonical.com
      department: charm_engineering
      email: tony.meyer@canonical.com
      team: charm_tech
  secscan: {}


artifacts:
  - name: 'ops'
    type: 'wheel'
    ssdlc_params:
        name: 'ops'
        version: ''
        channel: 'stable'

  - name: 'ops-scenario'
    type: 'wheel'
    ssdlc_params:
        name: 'ops-scenario'
        version: ''
        channel: 'stable'

  - name: 'ops-tracing'
    type: 'wheel'
    ssdlc_params:
        name: 'ops-tracing'
        version: ''
        channel: 'stable'
        cycle: '25.10'

  - name: 'ops-tools'
    type: 'wheel'
    ssdlc_params:
        name: 'ops-tools'
        version: ''
        channel: 'stable'
        cycle: '25.10'
