#!/bin/sh

set -e

flavour=html

if [ "$1" ]; then
    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
        flavour=help
    else
        flavour="$1"
    fi
    shift
fi

cd docs

sphinx-build -M "$flavour" . _build "$@"
