---
name: Update best practices documentation
description: Updates the best practices documentation with the latest practices
branding:
  icon: activity
  color: orange

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - run: |
        python .github/actions/update-best-practice-table/main.py > docs/best-practices-generated
      shell: bash
