"""
This type stub file was generated by pyright.
"""

class SimpleCookieJar:
    def __init__(self) -> None:
        ...
    
    def add(self, set_cookie): # -> None:
        ...
    
    def set(self, set_cookie): # -> None:
        ...
    
    def get(self, host): # -> str:
        ...
    


