"""
This type stub file was generated by pyright.
"""

from ._exceptions import *
from ._logging import *
from ._socket import *
from ._ssl_compat import *
from ._url import *

"""
_http.py
websocket - WebSocket client library for Python

Copyright 2022 engn33r

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
__all__ = ["proxy_info", "connect", "read_headers"]
class proxy_info:
    def __init__(self, **options) -> None:
        ...
    


def connect(url, options, proxy, socket):
    ...

def read_headers(sock): # -> tuple[int | None, dict[Unknown, Unknown], str | None]:
    ...

