"""
This type stub file was generated by pyright.
"""

_logger = ...
_traceEnabled = ...
__all__ = ["enableTrace", "dump", "error", "warning", "debug", "trace", "isEnabledForError", "isEnabledForDebug", "isEnabledForTrace"]
def enableTrace(traceable, handler=..., level=...): # -> None:
    """
    Turn on/off the traceability.

    Parameters
    ----------
    traceable: bool
        If set to True, traceability is enabled.
    """
    ...

def dump(title, message): # -> None:
    ...

def error(msg): # -> None:
    ...

def warning(msg): # -> None:
    ...

def debug(msg): # -> None:
    ...

def info(msg): # -> None:
    ...

def trace(msg): # -> None:
    ...

def isEnabledForError(): # -> bool:
    ...

def isEnabledForDebug(): # -> bool:
    ...

def isEnabledForTrace(): # -> Literal[False]:
    ...

