"""
This type stub file was generated by pyright.
"""

import argparse
import code

"""
wsdump.py
websocket - WebSocket client library for Python

Copyright 2022 engn33r

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
def get_encoding(): # -> Any | str:
    ...

OPCODE_DATA = ...
ENCODING = ...
class VAction(argparse.Action):
    def __call__(self, parser, args, values, option_string=...): # -> None:
        ...
    


def parse_args(): # -> Namespace:
    ...

class RawInput:
    def raw_input(self, prompt): # -> bytes:
        ...
    


class InteractiveConsole(RawInput, code.InteractiveConsole):
    def write(self, data): # -> None:
        ...
    
    def read(self): # -> bytes:
        ...
    


class NonInteractive(RawInput):
    def write(self, data): # -> None:
        ...
    
    def read(self): # -> bytes:
        ...
    


def main(): # -> None:
    ...

if __name__ == "__main__":
    ...
