[project]
name = "ops-tracing"
version = "3.9.0.dev0"
description = "The tracing facility for the Ops library."
requires-python = ">=3.10"
readme = "README.md"
license = "Apache-2.0"
authors = [
    {name="The Charm Tech team at Canonical Ltd."},
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries",
    "Framework :: OpenTelemetry",
]
dependencies = [
    "opentelemetry-api~=1.0",
    "opentelemetry-sdk~=1.30",
    "ops==3.9.0.dev0",
    "pydantic",
]

[project.urls]
"Repository" = "https://github.com/canonical/operator"
"Issues" = "https://github.com/canonical/operator/issues"
"Documentation" = "https://canonical.com/juju/docs/ops/latest/"
"Changelog" = "https://github.com/canonical/operator/blob/main/CHANGES.md"


[dependency-groups]
lint = [
    "ruff==0.16.0",
    "codespell==2.4.2",
    "pyright~=1.1",
]
unit = [
    "ops[testing]",
    "pytest~=9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 99
# FIXME
target-version = "py38"

[tool.ruff.format]
quote-style = "single"
exclude = ["ops_tracing/vendor/*"]

[tool.ruff.lint]
exclude = ["ops_tracing/vendor/*"]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "unsorted-imports",
    # pep8-naming
    "N",
    # flake8-builtins
    "A",
    # flake8-copyright
    "CPY",
    # pyupgrade
    "UP",
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # Ruff specific
    "RUF",
    # Perflint
    "PERF",
    # pyflakes-docstrings
    "D",
]
ignore = [
    # Incompatible with `blank-line-before-class`.
    "incorrect-blank-line-before-class",
    # Incompatible with `multi-line-summary-first-line`.
    "multi-line-summary-second-line",
    # We don't add a blank line after Args: in a function docstring.
    "missing-blank-line-after-last-section",
]

[tool.ruff.lint.per-file-ignores]
"test/*" = [
    # no need for docstring
    "D",
    "assert",
]

[tool.pyright]
exclude = [".tox", ".venv", "ops_tracing/vendor"]
extraPaths = ["..", "../testing"]
pythonVersion = "3.10" # check no python > 3.10 features are used
pythonPlatform = "All"
