[tox]
requires = tox>=4.2
env_list = lint, unit
skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
setenv =
  PY_COLORS=1
passenv =
  HOME
  PATH
  SCENARIO_SKIP_CONSISTENCY_CHECKS
  SCENARIO_BARE_CHARM_ERRORS


[testenv:py{3.10,3.12,3.14}-unit]
runner = uv-venv-lock-runner
base=unit

[testenv:unit]
dependency_groups = unit
commands = pytest {posargs}

[testenv:lint]
description = Check code against coding style standards
dependency_groups = lint, unit
commands =
    ruff check --preview
    ruff format --preview --check
    codespell
    pyright {posargs}

[testenv:format]
dependency_groups = lint
commands =
    ruff format --preview {toxinidir}
    ruff check --preview --fix {toxinidir}
