ATTACH_ALL_STORAGES = "ATTACH_ALL_STORAGES"
CREATE_ALL_RELATIONS = "CREATE_ALL_RELATIONS"
BREAK_ALL_RELATIONS = "BREAK_ALL_RELATIONS"
DETACH_ALL_STORAGES = "DETACH_ALL_STORAGES"
META_EVENTS = {
    "ATTACH_ALL_STORAGES",
    "CREATE_ALL_RELATIONS",
    "BREAK_ALL_RELATIONS",
    "DETACH_ALL_STORAGES",
}
