version: 2

build:
  os: ubuntu-24.04
  tools:
    # Python version shouldn't be important. Our Makefile controls the Python version.
    python: latest
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    build:
      html:
        - make -C docs html
