name: cla-check

on:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@5d1443b94417bd150ad234a82fe21f7340a25e4d  # v2.1.0
