name: Data Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  db-charm-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/postgresql-operator
            commit: 7afa2e867213a2230b520e8adde23e44701d6734  # 2025-01-24T16:00:14Z
          - charm-repo: canonical/postgresql-k8s-operator
            commit: ede755c941fc87a639ef615db6e5bcd57cb30188  # 2025-01-24T16:58:14Z
          - charm-repo: canonical/mysql-operator
            commit: 1fb61c1ee3e396cdce13d5e8155f2f32a860f89e  # rev339 rev338 2025-01-23T15:37:55Z
          - charm-repo: canonical/mysql-k8s-operator
            commit: 7c6b1206fcbc7324b72f413c5e63216e742a71a1  # 2025-01-24T00:25:29Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Checkout the operator repository
        uses: actions/checkout@v4
        with:
          path: myops

      - name: Install patch dependencies
        run: pip install poetry~=1.6

      - name: Update 'ops' dependency in test charm to latest
        run: |
          if [ -e "requirements.txt" ]; then
            sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
            echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt
          else
            sed -i -e "s/^ops[ ><=].*/ops = {path = \"myops\"}/" pyproject.toml
            poetry lock --no-update
          fi

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        run: tox -vve unit
