name: Dependency review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - name: Dependency review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
