name: Docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

permissions: {}

jobs:
  docs-spelling:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  # v8.0.0
      - name: Check spelling
        run: make -C docs spelling
