name: Observability Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  o11y-charm-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - charm-repo: canonical/alertmanager-k8s-operator
            commit: a502c204579977530f8c947c5dd2ab7e144ce905  # rev148 2025-01-22T12:11:12Z
          - charm-repo: canonical/prometheus-k8s-operator
            commit: aaa14059fe0b5926f707a35fba95ea60d70fc1f0 # 2025-01-23T20:01:25Z
            disabled: true # Waiting for an upstream PR: https://github.com/canonical/prometheus-k8s-operator/pull/639
          - charm-repo: canonical/grafana-k8s-operator
            commit: 4abcf11f721fe252458ad2ca872dab60031ea2a3  # rev134 2025-01-23T13:42:56Z
    steps:
      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.charm-repo }}
          ref: ${{ matrix.commit }}

      - name: Update 'ops' dependency in test charm to latest
        run: |
          sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
          echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit tests
        if: ${{ !(matrix.disabled) }}
        run: tox -vve unit

      - name: Run the charm's static analysis checks
        if: ${{ !(matrix.disabled) }}
        run: tox -vve static-charm
