name: Test Publish
on: [workflow_dispatch, workflow_call]

jobs:
  framework-tests:
    uses: ./.github/workflows/framework-tests.yaml
  observability-charm-tests:
    uses: ./.github/workflows/observability-charm-tests.yaml
  hello-charm-tests:
    uses: ./.github/workflows/hello-charm-tests.yaml
  build-n-publish:
    name: Build and Publish to Test PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: [framework-tests, observability-charm-tests, hello-charm-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install wheel
        run: pip install wheel
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Publish to test.pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
