name: TIOBE Quality Checks

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * 0'

permissions: {}

jobs:
  TICS:
    runs-on: [self-hosted, reactive, amd64, tiobe, noble]
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

        # We could store the report from the regular run, but this is cheap to do and keeps this isolated.
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
      - run: uv tool install tox --with tox-uv

      - name: Generate coverage report
        run: tox -e coverage,coverage-tracing,coverage-report

      - name: Install TIOBE and project dependencies
        run: |
          uv export --no-emit-project --frozen --no-hashes --group unit --group lint --group release --group tiobe > requirements.txt
          pip install -e . -r requirements.txt --break-system-packages

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@016a4d79f3027fe7b4a2901619a58c745ab7cadf  # v3.10.0
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: operator
          installTics: true
